# Generated by Django 5.1 on 2025-06-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0002_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateuserdetail',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporateuserdetail',
            name='email',
            field=models.EmailField(default='ee@ee.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corporateuserdetail',
            name='name',
            field=models.CharField(default='sger', max_length=255),
            preserve_default=False,
        ),
    ]
