# Generated by Django 5.1 on 2025-06-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0003_corporateuserdetail_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateuserdetail',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporateuserdetail',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
