# Generated by Django 5.1 on 2025-06-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDetail', '0004_corporateuserdetail_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
