# Generated by Django 5.1.4 on 2025-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0005_alter_user_is_approved"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("buyer_individual", "Buyer - Individual"),
                            ("buyer_corporate", "Buyer - Corporate"),
                            ("seller_individual", "Seller - Individual"),
                            ("seller_corporate", "Seller - Corporate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("free_credits", models.PositiveIntegerField(default=0)),
                ("paid_credits", models.PositiveIntegerField(default=0)),
                ("last_credit_purchase", models.DateTimeField(blank=True, null=True)),
                ("last_free_credit_reset", models.DateTimeField(auto_now_add=True)),
                ("free_credit_reset_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
