# Generated by Django 5.1.4 on 2025-08-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0006_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateuserdetail",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="corporateuserdetail",
            name="cin_number",
            field=models.CharField(blank=True, max_length=21, null=True),
        ),
        migrations.AddField(
            model_name="corporateuserdetail",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="corporateuserdetail",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
