# Generated by Django 5.1.4 on 2025-08-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0007_corporateuserdetail_aadhar_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
