# Generated by Django 5.1.4 on 2025-08-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0008_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
