# Generated by Django 5.1.4 on 2025-08-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0009_user_aadhar_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="corporateuserdetail",
            old_name="address",
            new_name="addressline1",
        ),
        migrations.AddField(
            model_name="corporateuserdetail",
            name="addressline2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
