# Generated by Django 5.1.4 on 2025-08-18 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0010_rename_address_corporateuserdetail_addressline1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="corporateuserdetail",
            name="address_pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
