# Generated by Django 5.1.4 on 2025-08-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0011_corporateuserdetail_address_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address_pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="addressline1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="addressline2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="corporateuserdetail",
            name="addressline1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="corporateuserdetail",
            name="pan_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
