# Generated by Django 5.1.4 on 2025-08-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0012_user_address_pincode_user_addressline1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
    ]
