# Generated by Django 5.1.4 on 2025-09-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("UserDetail", "0013_user_profile_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_category",
            field=models.BigIntegerField(null=True),
        ),
    ]
