# Generated by Django 5.1 on 2025-06-21 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('subcategory', models.CharField(max_length=15)),
                ('buyer_user_id', models.CharField(max_length=15)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('city_location', models.CharField(max_length=100)),
                ('state_location', models.CharField(max_length=100)),
                ('pincode_location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='requirement_attachments/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SellerListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('subcategory', models.CharField(max_length=15)),
                ('seller_user_id', models.CharField(max_length=15)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('city_location', models.CharField(max_length=100)),
                ('state_location', models.CharField(max_length=100)),
                ('pincode_location', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('auto_approved', 'Auto Approved'), ('approved', 'Approved'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auto_approved_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.BigIntegerField()),
                ('sub_category_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
