# Generated by Django 5.1.4 on 2025-07-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MarketPlace", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerlisting",
            name="revived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
