# Generated by Django 5.1.4 on 2025-07-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MarketPlace", "0002_sellerlisting_revived_at_sellerlisting_valid_until"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buyerrequirement",
            old_name="expires_at",
            new_name="revived_at",
        ),
        migrations.RemoveField(
            model_name="buyerrequirement",
            name="attachment",
        ),
        migrations.RemoveField(
            model_name="buyerrequirement",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="buyerrequirement",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="buyerrequirement",
            name="is_urgent",
        ),
        migrations.AddField(
            model_name="buyerrequirement",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("requirementfulfilled", "Requirementfulfilled"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="buyerrequirement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="buyerrequirement",
            name="valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
