# Generated by Django 5.1.4 on 2025-07-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MarketPlace", "0003_rename_expires_at_buyerrequirement_revived_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerlisting",
            name="featured_image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="gallery_images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
