# Generated by Django 5.1.4 on 2025-08-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MarketPlace", "0004_sellerlisting_featured_image_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="buyerrequirement",
            name="category",
        ),
        migrations.RemoveField(
            model_name="buyerrequirement",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="sellerlisting",
            name="category",
        ),
        migrations.RemoveField(
            model_name="sellerlisting",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="buyerrequirement",
            name="category_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="buyerrequirement",
            name="subcategory_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="category_id",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="subcategory_id",
            field=models.BigIntegerField(null=True),
        ),
    ]
