# Generated by Django 5.1.4 on 2025-08-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MarketPlace", "0005_remove_buyerrequirement_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerlisting",
            name="priceperunit",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="seller_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
