# Generated by Django 5.1.4 on 2025-08-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MarketPlace", "0006_sellerlisting_priceperunit_sellerlisting_seller_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerlisting",
            name="waste_packed_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bags", "Bags"),
                    ("box", "Box"),
                    ("lumps", "Lumps"),
                    ("rolls", "Rolls"),
                ],
                default="bags",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sellerlisting",
            name="waste_stored",
            field=models.CharField(
                blank=True,
                choices=[("indoor", "Indoor"), ("outdoor", "Outdoor")],
                default="indoor",
                max_length=10,
                null=True,
            ),
        ),
    ]
