# Generated by Django 5.1.4 on 2025-08-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MarketPlace", "0007_sellerlisting_waste_packed_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerlisting",
            name="listing_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
